on:
  push:
    branches: [ "main" ]
    paths:
      - 'app-source-code/frontend/**'
    paths-ignore:
      - '.github/workflows/backend.yaml'
      - '.github/workflows/eks.yaml'  
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app-source-code/frontend/**'
  workflow_dispatch: